wandb_version: 1

lr:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694352755.754249
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      2:
      - 1
      - 41
      - 50
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.15.9
      8:
      - 3
      - 5
