defaults:
  - algorithm: jtt
  - model: linear_classifier
  - datamodule: regnet_representation
  - optimizer: adam
  - loss: cross_entropy
  - scheduler: ReduceLROnPlateau
  - override hydra/job_logging: custom

device: cuda