defaults:
  - algorithm: afr
  - model: linear_classifier
  - datamodule: resnet50_representation
  - optimizer: adam
  - loss: cross_entropy
  - scheduler: ReduceLROnPlateau
  - override hydra/job_logging: custom

device: cuda:0