defaults:
  - algorithm: standard_training
  - model: cnn
  - dataset: waterbirds_images
  - optimizer: sgd
  - optional dataset_model: ${algorithm}_${dataset}_${model}_${optimizer}
  - override hydra/job_logging: custom  

loss_function:
  _target_: torch.nn.CrossEntropyLoss