_target_: src.model.AFR
in_features: ${datamodule.data_config.in_features}  
num_classes: ${datamodule.data_config.num_classes}
  
gamma: 1
num_epochs: 1

weights_path: ${oc.env:WEIGHTS_DIR}/second_model.pth