name: dino_v2_representation

data_config: 
  _target_:  src.datamodule.EncodingDataModule

  in_features: 768
  batch_size: 8
  num_classes: 2

  train_path: ${oc.env:DATA_ROOT}/dino_v2/train.npz
  test_path: ${oc.env:DATA_ROOT}/dino_v2/test.npz
  val_path: ${oc.env:DATA_ROOT}/dino_v2/val.npz


  
