name: regnet_representation

data_config:
  _target_:  src.datamodule.EncodingDataModule

  in_features: 7392
  batch_size: 16
  num_classes: 2

  train_path: ${oc.env:DATA_ROOT}/swag_pretrained_regnety_128gf_in1k/train.npz
  test_path: ${oc.env:DATA_ROOT}/swag_pretrained_regnety_128gf_in1k/test.npz
  val_path: ${oc.env:DATA_ROOT}/swag_pretrained_regnety_128gf_in1k/val.npz

  training_type: ${training_type.name}  