name: resnet50_representation

data_config:
  _target_:  src.datamodule.EncodingDataModule

  in_features: 2048
  batch_size: 8
  num_classes: 2

  train_path: ${oc.env:DATA_ROOT}/resnet50/train.npz
  test_path: ${oc.env:DATA_ROOT}/resnet50/test.npz
  val_path: ${oc.env:DATA_ROOT}/resnet50/val.npz