name: waterbirds

data_config:
  _target_:  datamodule.image_data.DataModule

  download: True
  batch_size: 16
  num_classes: 2
  in_channel: 3

  root_dir: ${oc.env:DATA_ROOT}/waterbirds_v1.0

data_formats: 
  - image
